/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCell: typeof import('./components/common/ActionCell.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Breadcrumb: typeof import('./components/common/Breadcrumb.vue')['default']
    ConfirmDelete: typeof import('./components/common/ConfirmDelete.vue')['default']
    DataFilter: typeof import('./components/common/DataFilter.vue')['default']
    FormRepeater: typeof import('./components/common/FormRepeater.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Loading: typeof import('./components/common/Loading.vue')['default']
    ProductCreate: typeof import('./components/product/ProductCreate.vue')['default']
    ProductForm: typeof import('./components/product/ProductForm.vue')['default']
    ProductList: typeof import('./components/product/ProductList.vue')['default']
    ProductShow: typeof import('./components/product/ProductShow.vue')['default']
    ProductUpdate: typeof import('./components/product/ProductUpdate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./components/common/Toolbar.vue')['default']
  }
}
